### ISSUE TITLE
Implement -17

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/swid#14]
Looking at https://tools.ietf.org/rfcdiff?url2=draft-ietf-sacm-coswid-17.txt it seems like we need to move around a number of smallish things:

* payload or evidence cardinality:
```
payload-or-evidence //= ( payload => payload-entry )
payload-or-evidence //= ( evidence => evidence-entry )
```

* ownership type (was unsigned):
```
$ownership /= int / text
```

* use type (was unsigned):
```
$use /= int / text	
```

* file-entry size type:
```
? size => uint,
```

* directory-entry path-elements is optional:
```
? path-elements => { path-elements-group },
```

* evidence-entry date type:
```
? date => integer-time,
```

* any-uri type
```
any-uri = uri
```

* 7.  Signed CoSWID Tags (currently not implemented)

* 8.  Tagged CoSWID Tags

**Comment by thomas-fossati** [comment]
-18 is out and we should recheck [the diff](https://tools.ietf.org/rfcdiff?url1=draft-ietf-sacm-coswid-16.txt&url2=draft-ietf-sacm-coswid-18.txt).

**Comment by carl-wallace** [comment]
Give a look at -21 as well. The index values for shared and abandon changed in the CDDL (the CDDL and prose had been disaligned for a long time it looks like). This is a breaking change.

**Comment by thomas-fossati** [comment]
@CodingVoid has provided an implementation of -21 in #33
